### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by Basti890** [emestee/dayz-epoch-linux-server-magic#12]
$ git clone git@github.com:emestee/dayz-epoch-linux-server-magic.git
Klone nach 'dayz-epoch-linux-server-magic'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I can't download it :O

**Comment by emestee** [comment]
Clone the HTTP URL:

https://github.com/emestee/dayz-epoch-linux-server-magic.git

**Comment by Clevero** [comment]
probably you haven't set up a ssh public key in your github profile. without that you cannot download anything over ssh from github
